plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.detekt)
}

android {
    namespace = "redtoss.creativity.cerebro"
    compileSdk = 37

    defaultConfig {
        applicationId = "redtoss.creativity.cerebro"
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")

            // ###################################################################
            // ##  INTERIM — NOT SHIPPABLE. DO NOT DISTRIBUTE THIS BUILD TYPE.  ##
            // ###################################################################
            // The project has no release signing config yet, and an unsigned APK
            // cannot be installed, which makes R8 impossible to verify on a device.
            // Debug-signing keeps the release variant installable for testing.
            //
            // The debug keystore is auto-generated, shared across every Android
            // project on the machine, and its password is public knowledge. An APK
            // signed with it can be trivially re-signed by anyone.
            //
            // This MUST be replaced with a real signing config before any
            // distribution (Play Store, side-load, internal testing track).
            // ###################################################################
            signingConfig = signingConfigs.getByName("debug")
        }
        debug {
            // Distinct application id so a debug build can sit next to a release
            // build on the same device instead of replacing it.
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    lint {
        abortOnError = true
        warningsAsErrors = true
        checkReleaseBuilds = true
        checkDependencies = true
        // Cerebro is English-only by product decision, so user-facing strings live
        // inline in the Composables rather than in strings.xml. Revisit this if
        // localisation ever becomes a goal.
        disable += "HardcodedText"
        // Always a false positive here: lint spell-checks the base64 Google Fonts
        // certificate blob in res/values/font_certs.xml. Nothing to fix, ever.
        disable += "Typos"

        // Real but deferred: demoted to hints so they stay visible in the lint report
        // without gating the build. Each needs a res/ change, tracked as follow-up work.
        informational += "PrivateResource"        // app re-declares ui-text-google-fonts' cert arrays
        informational += "UnusedResources"        // leftover template colors, drawables and app_motto
        informational += "IconDuplicates"         // ic_launcher and ic_launcher_round are identical
        informational += "MonochromeLauncherIcon" // adaptive icon has no monochrome layer yet
        informational += "IconLocation"           // cerebro_logo.png lives in densityless res/drawable
    }
    buildFeatures {
        compose = true
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// Kept outside `android { }` on purpose: detekt is a plain Gradle plugin, not an
// Android DSL extension.
detekt {
    buildUponDefaultConfig = true
    config.setFrom("$rootDir/config/detekt/detekt.yml")
    parallel = true
    // Pre-existing violations only. Every rule stays active, so new code cannot
    // add findings; the baseline shrinks to nothing and is deleted once the
    // follow-up formatting/cleanup work lands.
    baseline = file("$rootDir/config/detekt/baseline.xml")
}

// ui/theme2 is a verbatim Material Theme Builder export (colour tokens and the
// generated ColorSchemes). It is regenerated by the tool, not edited by hand,
// so linting it only produces findings nobody may act on. Applied to both the
// analysis task and the baseline task so the two see the same source set.
tasks.withType<io.gitlab.arturbosch.detekt.DetektCreateBaselineTask>().configureEach {
    exclude("**/ui/theme2/**")
}

tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    exclude("**/ui/theme2/**")

    reports {
        html.required.set(true)
        sarif.required.set(true)
        xml.required.set(false)
        txt.required.set(false)
        md.required.set(false)
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.material.icons.core)
    implementation(libs.androidx.google.fonts)
    implementation(libs.androidx.navigation)
    implementation(libs.kotlinx.serialization)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)

    detektPlugins(libs.detekt.formatting)
}
// Workaround for AGP 9.4.0 + R8 + Compose.
//
// Enabling minification registers `produceReleaseComposeMapping`, which resolves
// org.jetbrains.kotlin:compose-group-mapping. AGP asks for that artifact at its own
// bundled Kotlin version, 2.2.10 — a version that was never published to Maven
// Central, where the artifact only starts at 2.3.0-Beta1. The build therefore fails
// to resolve it the moment `isMinifyEnabled` is turned on.
//
// Pin it to the Kotlin version this project actually compiles with, which does exist.
// Remove once AGP requests a published version by itself.
configurations.configureEach {
    if (name.contains("composeMapping", ignoreCase = true)) {
        resolutionStrategy.force("org.jetbrains.kotlin:compose-group-mapping:${libs.versions.kotlin.get()}")
    }
}
