name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "feature/CI_CD" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        run: ./gradlew build

  static-code-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run static code analysis
        run: echo "Run Detekt or something"