name: Android CI

on:
  push:
    branches: [ "main", "feature/CI_CD" ]
  pull_request:
    branches: [ "main", "feature/CI_CD" ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Log all files
        run: ls -al > ./allFiles.txt

#      - name: Build with Gradle
#        run: ./gradlew build

      - name: Cache build project
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-build-project
        with:
          path: ./allFiles.txt
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys:
            ${{ runner.os }}-build-${{ env.cache-name }}

  second-job:
    needs: android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Load cached project
        id: restore-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-build-project
        with:
          path: ./allFiles.txt
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true'}}
        name: Project was reload from cache
        run: echo "Project was not cached"
        continue-on-error: false

      - name: Final step
        run: echo "Finished"
